###
### VARIABLES DE PRUEBA
###
#POST http://{{hostname}}/persona/validuser HTTP/1.1
# @hostname = localhost/api/appundav
@hostname = "172.16.1.43/api/appundav"

### ESTUDIANTES DE PRUEBA

# @USUARIO = "0-23156651"
# @PASSWORD = "Desarrollo2025+"
# @PERSONA_ID = 6451

@USUARIO = "43877860"
@PASSWORD = "abc123"
@PERSONA_ID = 57481

@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0Mzg3Nzg2MCIsImlhdCI6MTc0OTEzODIwNywiZXhwIjoxNzQ5MTQxODA3fQ.VJroEmw9ieQrUdZ2SgOYlasSy0bIGFSjoqiiD6HEU0U

###
### OBTIENE TOKEN (login)
###
POST http://172.16.1.43/api/appundav/persona/validuser HTTP/1.1
Content-Type: application/json

{
    "usuario": {{USUARIO}},
    "clave": {{PASSWORD}}
}

#####################################################################
### PERSONA 

###
### SHOW PERSONA
GET http://172.16.1.43/api/appundav/persona/{{PERSONA_ID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
### SHOW TODAS LAS PERSONA
GET http://172.16.1.43/api/appundav/persona HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
### DELETE PERSONA (BORRADO LOGICO)
DELETE http://172.16.1.43/api/appundav/persona/{{PERSONA_ID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


#####################################################################
### CRUD NOTAS
#####################################################################
###
### CREATE ANOTACION PARA UNA PERSONA
###
POST http://172.16.1.43/api/appundav/anotaciones HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "persona": {{PERSONA_ID}},
    "titulo": "jhgkhjngvjhv para examen Mock!",
    "detalle": "Estudiar, Estudiar, Estudiar.... y mas estudiar", 
    "fecha_alerta": "2026-03-11 18:00:00"
}


###
### SHOW TODAS LAS ANOTACIONES DE UNA PERSONA
GET http://172.16.1.43/api/appundav/anotaciones/{{PERSONA_ID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###
### TRAE ANOTACION PUNTUAL DE UNA PERSONA
GET  http://172.16.1.43/api/appundav/anotaciones/{{PERSONA_ID}}/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###
### UPDATE
###
PUT http://172.16.1.43/api/appundav/anotaciones/{{PERSONA_ID}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "persona": {{PERSONA_ID}},
    "titulo": "Titulo WWWWWWWWWWWWWWW",
    "detalle": "Estudiar SARASA WWWWWWWWWWWWWWWWWWW.", 
    "fecha_alerta": "2026-03-11 18:00:00"
}

###
### DELETE logico - actualiza fecha de borrado. deleted_at
###
DELETE http://172.16.1.43/api/appundav/anotaciones/{{PERSONA_ID}}/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

#####################################################################
### ENVIA MAIL AL ESTUDIANTE/PERSONA (PREVIO DEFINIR TOKEN)
###
GET http://172.16.1.43/api/appundav/persona/{{PERSONA_ID}}/sendmail HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}